"http://{default}/":
    type: upstream
    upstream: "app:http"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"

"http://solr.{default}/":
    type: upstream
    upstream: "solrsearch:http"